### ISSUE TITLE
Bug: All players see a Sentinel fabled in play, even if not selected

### ISSUE THREAD

**Issue by AdmiralGT** [bra1n/townsquare#85] opened 2021-01-06 19:46 UTC
**Describe the bug**
When joining a game, players see the Sentinel in play in the Fabled section.
![image](https://user-images.githubusercontent.com/3476614/103813333-d6241d80-5057-11eb-81e3-f3ba2fe21e70.png)

**To Reproduce**
1. Join a game
2. Look at top left

**Expected behavior**
Players only see the actual Fabled roles in play

**Comment by bra1n** [comment] 2021-01-06 19:53
Hi @AdmiralGT, I can't reproduce this. When I join a game that doesn't have any Fabled selected by the host, I don't see a Fabled as a player either. Do you have a game session name for me so I can look at the logs?

**Comment by AdmiralGT** [comment] 2021-01-06 20:01
Hmm, I've tried to reproduce by creating a new game and couldn't reproduce. I suspect the fabled has been carried over to the host from a previous game. If I join a session with the Sentinel fabled, it doesn't remove the fabled when I leave the session so I suspect the host has played in a session with a Sentinel and never removed it before hosting. It would be nice if hosting a game reset all Fabled since it seems easy to do (since the game remembers sessions)

**Comment by bra1n** [comment] 2021-01-06 20:57
> Hmm, I've tried to reproduce by creating a new game and couldn't reproduce. I suspect the fabled has been carried over to the host from a previous game. If I join a session with the Sentinel fabled, it doesn't remove the fabled when I leave the session so I suspect the host has played in a session with a Sentinel and never removed it before hosting. It would be nice if hosting a game reset all Fabled since it seems easy to do (since the game remembers sessions)

Some custom scripts do set a Fabled when loading, so removing a Fabled whenever you host a session would be counter-intuitive then.  However, clearing players and / or characters now also clears Fabled (when not playing in a session)

**Comment by bra1n** [comment] 2021-01-06 21:37
Closing this with https://github.com/bra1n/townsquare/commit/1f4a37ab5cecbfac372b4a2f344555942b25171b

**Closed by bra1n** 2021-01-06 21:37 UTC
Labels: bug, feedback needed
