### ISSUE TITLE
Bug: Custom Script custom image doesn't appear when joining

### ISSUE THREAD

**Issue by magroader** [bra1n/townsquare#103] opened 2021-01-23 19:17 UTC
**Describe the bug**
We played a game with a custom script with a custom central image, and the joining players did not see the custom image after they joined. The Host could see the image.

**To Reproduce**
1. Create a custom script with a custom image
2. Load the script
3. Host a game
4. (Other person) load the script
5. (Other person) Notice you can see the image
6. (Other person) join the host's game
**7. (Other person) Notice you can no longer see the image**

**Expected behavior**
The other person would see the custom icon after joining

**Comment by JulGvoz** [comment] 2021-01-24 13:38
Seems like intended behaviour, see #93 , #75

**Comment by JulGvoz** [comment] 2021-01-24 13:39
On the other hand - loading the script before hand, then joining the game does erase the middle icon. Seems like a bug

**Comment by bra1n** [comment] 2021-01-24 21:40
As @JulGvoz pointed out, this is *currently* the intended behaviour. I'm working on a fix for this (plus homebrew image support), but it will take some time because it requires a few more changes.

**Comment by bra1n** [comment] 2021-01-24 21:41
Duplicates #74

**Closed by bra1n** 2021-01-24 21:40 UTC
Labels: bug
